#!/usr/bin/env bash
set -euo pipefail
printf '\nhost replication replicator all scram-sha-256\n' >> "$PGDATA/pg_hba.conf"
psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set=ON_ERROR_STOP=1 --set=rw="$APP_RW_PASSWORD" --set=ro="$APP_RO_PASSWORD" --set=repl="$REPLICATOR_PASSWORD" --set=db="$POSTGRES_DB" <<'SQL'
CREATE ROLE app_rw LOGIN PASSWORD :'rw' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE app_ro LOGIN PASSWORD :'ro' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE replicator LOGIN REPLICATION PASSWORD :'repl' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
ALTER ROLE app_ro SET default_transaction_read_only = on;
REVOKE CREATE,TEMPORARY ON DATABASE :"db" FROM PUBLIC;
GRANT CONNECT ON DATABASE :"db" TO app_rw,app_ro;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
SQL
