port: 4222
server_name: marketmesh-dev
jetstream { store_dir: "/data/jetstream", max_mem_store: 64MB, max_file_store: 128MB }
max_payload: 16384
tls { cert_file: "/secrets/cert.pem", key_file: "/secrets/key.pem", ca_file: "/secrets/ca.pem", min_version: "1.3", verify_and_map: true, timeout: 2 }
accounts { MARKETMESH { jetstream: enabled
 users: [
 { user: "auth-publisher@marketmesh.test", permissions: { publish: { allow: ["auth.account.registered.v1"] }, subscribe: { allow: ["_INBOX.>"] } } },
 { user: "user-consumer@marketmesh.test", permissions: { publish: { allow: ["$JS.API.CONSUMER.INFO.AUTH_REGISTRATION.USER_PROFILES_V1", "$JS.API.CONSUMER.MSG.NEXT.AUTH_REGISTRATION.USER_PROFILES_V1", "$JS.ACK.AUTH_REGISTRATION.USER_PROFILES_V1.>"] }, subscribe: { allow: ["_INBOX.>"] } } },
 { user: "fixture-admin@marketmesh.test", permissions: { publish: { allow: [">"] }, subscribe: { allow: [">"] } } }
] } }
